name: "Update licenses"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month

jobs:
  update-licenses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Update licenses list
        run: |
          poetry run python src/poetry/core/spdx/helpers.py

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.POETRY_TOKEN_APP_ID }}
          private_key: ${{ secrets.POETRY_TOKEN_APP_KEY }}

      - name: Create PR if necessary
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Automated licenses list update"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "license-autoupdate"
          title: "Automated licenses list update"
          body: "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
