name: Update Licenses

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month

# we create the token we need later on
permissions: {}

jobs:
  update-licenses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Update licenses list
        run: |
          poetry run python src/poetry/core/spdx/helpers.py
          poetry run pre-commit run --all-files || :

      - name: Generate token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.POETRY_TOKEN_APP_ID }}
          private-key: ${{ secrets.POETRY_TOKEN_APP_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create PR if necessary
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Automated licenses list update"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "license-autoupdate"
          title: "Automated licenses list update"
          body: "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
